In [3]:
import pandas as pd
import numpy as np
from collections import Counter
from google.colab import files

uploaded = files.upload()


df = pd.read_csv("iris_dataset.csv")
df


Saving iris_dataset.csv to iris_dataset.csv


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [6]:
X = df[["sepal length (cm)", "sepal width (cm)", "petal length (cm)", "petal width (cm)"]].values
y = df["target"].values


In [27]:
P_test = X[149]
y_test_true = y[149]

X_train = X[:149]
y_train = y[:149]

P_test, y_test_true

(array([5.9, 3. , 5.1, 1.8]), np.int64(2))

In [8]:
def dist(a, b):
    return np.sqrt(np.sum((a - b)**2))


In [9]:
distances = np.array([dist(P_test, p) for p in X_train])


In [10]:
k = 3
idx = distances.argsort()[:k]
neighbors = y_train[idx]
neighbors


array([2, 2, 2])

In [11]:
pred_k3_raw = Counter(neighbors).most_common(1)[0][0]
pred_k3_raw


np.int64(2)

In [14]:
mu = X_train.mean(axis=0)
sigma = X_train.std(axis=0)

print("mu is:", mu)
print("sigma is:", sigma)


mu is: [5.84295302 3.05771812 3.74899329 1.19530201]
sigma is: [0.82805303 0.43584081 1.76184838 0.76063693]


In [17]:
X_train_norm = (X_train - mu) / sigma


In [19]:
df_temp_raw = pd.DataFrame(X_train)
df_temp_norm = pd.DataFrame(X_train_norm)
df_temp = pd.concat([df_temp_raw, df_temp_norm], axis=1)
df_temp

0    1    2    3         0         1         2         3
0    5.1  3.5  1.4  0.2 -0.897229  1.014778 -1.333255 -1.308511
1    4.9  3.0  1.4  0.2 -1.138759 -0.132429 -1.333255 -1.308511
2    4.7  3.2  1.3  0.2 -1.380290  0.326454 -1.390014 -1.308511
3    4.6  3.1  1.5  0.2 -1.501055  0.097012 -1.276496 -1.308511
4    5.0  3.6  1.4  0.2 -1.017994  1.244220 -1.333255 -1.308511
..   ...  ...  ...  ...       ...       ...       ...       ...
144  6.7  3.3  5.7  2.5  1.035015  0.555895  1.107364  1.715270
145  6.7  3.0  5.2  2.3  1.035015 -0.132429  0.823571  1.452333
146  6.3  2.5  5.0  1.9  0.551954 -1.279637  0.710054  0.926458
147  6.5  3.0  5.2  2.0  0.793484 -0.132429  0.823571  1.057927
148  6.2  3.4  5.4  2.3  0.431189  0.785337  0.937088  1.452333

[149 rows x 8 columns]

In [20]:
P_test_norm = (P_test - mu) / sigma


In [28]:
distances_norm = np.array([dist(P_test_norm, p) for p in X_train_norm])


In [29]:
idx_norm = distances_norm.argsort()[:3]
neighbors_norm = y_train[idx_norm]
neighbors_norm


array([2, 2, 1])

In [30]:
pred_k3_norm = Counter(neighbors_norm).most_common(1)[0][0]
pred_k3_norm


np.int64(2)

In [31]:
print("True class:", y_test_true)
print("Predicted (no normalization):", pred_k3_raw)
print("Predicted (Z-score normalization):", pred_k3_norm)


True class: 2
Predicted (no normalization): 2
Predicted (Z-score normalization): 2
