In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [2]:
from google.colab import files
uploaded = files.upload()


Saving iris_dataset.csv to iris_dataset.csv


In [3]:
df = pd.read_csv("iris_dataset.csv")
df


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [4]:
df.columns


Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)', 'target'],
      dtype='object')

In [7]:
df[["sepal length (cm)", "sepal width (cm)"]]

sepal length (cm)  sepal width (cm)
0                  5.1               3.5
1                  4.9               3.0
2                  4.7               3.2
3                  4.6               3.1
4                  5.0               3.6
..                 ...               ...
145                6.7               3.0
146                6.3               2.5
147                6.5               3.0
148                6.2               3.4
149                5.9               3.0

[150 rows x 2 columns]

In [11]:
x = df[["sepal length (cm)", "sepal width (cm)"]].values
x.shape

(150, 2)

In [12]:
x

array([[5.1, 3.5],
       [4.9, 3. ],
       [4.7, 3.2],
       [4.6, 3.1],
       [5. , 3.6],
       [5.4, 3.9],
       [4.6, 3.4],
       [5. , 3.4],
       [4.4, 2.9],
       [4.9, 3.1],
       [5.4, 3.7],
       [4.8, 3.4],
       [4.8, 3. ],
       [4.3, 3. ],
       [5.8, 4. ],
       [5.7, 4.4],
       [5.4, 3.9],
       [5.1, 3.5],
       [5.7, 3.8],
       [5.1, 3.8],
       [5.4, 3.4],
       [5.1, 3.7],
       [4.6, 3.6],
       [5.1, 3.3],
       [4.8, 3.4],
       [5. , 3. ],
       [5. , 3.4],
       [5.2, 3.5],
       [5.2, 3.4],
       [4.7, 3.2],
       [4.8, 3.1],
       [5.4, 3.4],
       [5.2, 4.1],
       [5.5, 4.2],
       [4.9, 3.1],
       [5. , 3.2],
       [5.5, 3.5],
       [4.9, 3.6],
       [4.4, 3. ],
       [5.1, 3.4],
       [5. , 3.5],
       [4.5, 2.3],
       [4.4, 3.2],
       [5. , 3.5],
       [5.1, 3.8],
       [4.8, 3. ],
       [5.1, 3.8],
       [4.6, 3.2],
       [5.3, 3.7],
       [5. , 3.3],
       [7. , 3.2],
       [6.4, 3.2],
       [6.9,

In [13]:
y = df["target"].values
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [14]:
y.shape

(150,)

In [16]:
P_test = x[149]
y_test_true = y[149]


In [17]:
P_test


array([5.9, 3. ])

In [18]:
y_test_true

np.int64(2)

In [21]:
x_train = x[:149]
y_train = y[:149]


In [23]:
def euclidean_distance(a, b):
    return np.sqrt(np.sum((a - b)**2))


In [25]:
distances = np.array([euclidean_distance(P_test, point) for point in x_train])
distances

array([0.94339811, 1.        , 1.21655251, 1.30384048, 1.08166538,
       1.02956301, 1.36014705, 0.98488578, 1.50332964, 1.00498756,
       0.86023253, 1.17046999, 1.1       , 1.6       , 1.00498756,
       1.41421356, 1.02956301, 0.94339811, 0.82462113, 1.13137085,
       0.64031242, 1.06301458, 1.43178211, 0.85440037, 1.17046999,
       0.9       , 0.98488578, 0.86023253, 0.80622577, 1.21655251,
       1.1045361 , 0.64031242, 1.30384048, 1.26491106, 1.00498756,
       0.92195445, 0.64031242, 1.16619038, 1.5       , 0.89442719,
       1.02956301, 1.56524758, 1.5132746 , 1.02956301, 1.13137085,
       1.1       , 1.13137085, 1.31529464, 0.92195445, 0.9486833 ,
       1.11803399, 0.53851648, 1.00498756, 0.80622577, 0.63245553,
       0.28284271, 0.5       , 1.16619038, 0.70710678, 0.76157731,
       1.3453624 , 0.        , 0.80622577, 0.2236068 , 0.31622777,
       0.80622577, 0.3       , 0.31622777, 0.85440037, 0.58309519,
       0.2       , 0.28284271, 0.64031242, 0.28284271, 0.50990

In [28]:
index_min = distances.argmin()
index_min
print(distances[index_min])

0.0


In [27]:
nearest_point = x_train[index_min]
nearest_point

array([5.9, 3. ])

In [30]:
idx_min = distances.argmin()
nearest_point = x_train[idx_min]
predicted_class_k1 = y_train[idx_min]


In [31]:
print("Test Point =", P_test)
print("Nearest Neighbor =", nearest_point)
print("Predicted Class (k=1) =", predicted_class_k1)
print("True Class =", y_test_true)


Test Point = [5.9 3. ]
Nearest Neighbor = [5.9 3. ]
Predicted Class (k=1) = 1
True Class = 2


In [66]:
k = 3
idx_sorted = distances.argsort()[:k]
idx_sorted

array([ 61, 138,  78])

In [67]:
distances[idx_sorted]

array([0.        , 0.1       , 0.14142136])

In [68]:
nearest_classes = y_train[idx_sorted]
nearest_classes


array([1, 2, 1])

In [69]:
from collections import Counter

print(Counter(nearest_classes))

Counter({np.int64(1): 2, np.int64(2): 1})


In [70]:
predicted_class_k3 = Counter(nearest_classes).most_common(1)[0][0]
predicted_class_k3

np.int64(1)

In [71]:
print("3 nearest neighbors classes:", nearest_classes)
print("Predicted class (k=3):", predicted_class_k3)
print("True class:", y_test_true)


3 nearest neighbors classes: [1 2 1]
Predicted class (k=3): 1
True class: 2
